export const getJobData = (t) => [
  {
    id: 5,
    date: t("freelance.date"),
    title: t("freelance.title"),
    company: t("freelance.company"),
    iconBg: "#9e8895",
    iconUrl: "/images/experience/matintaherzadeh.png",
    points: [
      t("freelance.points.1"),
      t("freelance.points.2"),
      t("freelance.points.3"),
    ],
  },
  {
    id: 4,
    date: t("roshan.date"),
    title: t("roshan.title"),
    company: t("roshan.company"),
    iconBg: "#facc15",
    iconUrl: "/images/experience/roshan.png",
    points: [
      t("roshan.points.1"),
      t("roshan.points.2"),
      t("roshan.points.3"),
      t("roshan.points.4"),
    ],
  },
  {
    id: 2,
    date: t("myadegaran.date"),
    title: t("myadegaran.title"),
    company: t("myadegaran.company"),
    iconBg: "#78eb9a",
    iconUrl: "/images/experience/myadegaran.png",
    points: [t("myadegaran.points.1"), t("myadegaran.points.2")],
  },
  {
    id: 3,
    date: t("york_building.date"),
    title: t("york_building.title"),
    company: t("york_building.company"),
    iconBg: "#e3e6e4",
    iconUrl: "/images/experience/yorkbuilding.png",
    points: [t("york_building.points.1"), t("york_building.points.2")],
  },

  {
    id: 1,
    date: t("parsian_farhang.date"),
    title: t("parsian_farhang.title"),
    company: t("parsian_farhang.company"),
    iconBg: "#d3dbe8",
    iconUrl: "/images/experience/parsianFarhang.png",
    points: [t("parsian_farhang.points")],
  },
];
