// app/layout.js (RootLayout)
import "@/app/styles/global.css";
import Header from "./components/header/Header";

export const metadata = {
  title: "Matin Taherzadeh - متین طاهرزاده",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body
        className="antialiased
          bg-linear-to-r from-white to-[#ffe6ff]
          overflow-x-hidden text-black font-shabnam"
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
