import Header from "./components/header/Header";
import "./styles/global.css";

export const metadata = {
  title: "Matin Taherzadeh - متین طاهرزاده",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" className="scroll-smooth">
      <body
        className={`antialiased 
          bg-gradient-to-r from-white to-[#ffe6ff] 
          overflow-x-hidden text-black font-shabnam`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
