import "@/app/styles/global.css";

export const metadata = {
  title: "Matin Taherzadeh - متین طاهرزاده",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <>{children}</>;
}
