import { hasLocale, NextIntlClientProvider } from "next-intl";
import Header from "../components/header/Header";
import "@/app/styles/global.css";
import { routing } from "../../i18n/routing";
import { notFound } from "next/navigation";

export const metadata = {
  title: "Matin Taherzadeh - متین طاهرزاده",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang="fa" dir="rtl" className="scroll-smooth">
      <body
        className={`antialiased 
          bg-linear-to-r from-white to-[#ffe6ff] 
          overflow-x-hidden text-black font-shabnam`}
      >
        <NextIntlClientProvider>
          <Header />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
